### ISSUE TITLE
proxies?

### ISSUE THREAD

**Issue by joshuacox** [xxyQwQ/ComfyBench#13]
I tried to comment out the proxies in the config.yaml but that did not work either?

my config file looks like this:

```
# proxy settings
proxy:
  http_proxy: null
  https_proxy: null

# comfyui settings
comfyui:
  comfyui_address: "10.64.201.1:8188"
  execution_timeout: 300

# embedding api for retrieval
embedding:
  base_url: "10.64.201.1:11434"
  api_key: "null123"
  model_name: "mxbai-embed-large:latest"

# completion api for agent
completion:
  base_url: "10.64.201.1:11434"
  api_key: "null123"
  model_name: "llama3.3:latest"
  hyper_parameter:
    temperature: 0.0
    top_p: 1.0

# vision api for evaluation
vision:
  base_url: "10.64.201.1:11434"
  api_key: "null123"
  model_name: "llama3.3:latest"
  hyper_parameter:
    temperature: 0.0
    top_p: 1.0
```

```
python main.py \
    --instruction "task-instruction" \
    --agent_name "comfy" \
    --save_path "/tmp/output12"
-------------------------------- Program Status --------------------------------
creating pipeline...

-------------------------------- Program Status --------------------------------
generating workflow...

------------------------------- Task Instruction -------------------------------
task-instruction

------------------------------- Analyzer Prompt --------------------------------

## Task

ComfyUI uses workflows to create and execute Stable Diffusion pipelines so that users can design their own workflows to generate highly customized artworks. ComfyUI workflows can be formulated into the equivalent Python code, where each statement represents the execution of a single node. You are an expert in ComfyUI, helping users to design workflows according to their requirements.

Now you are required to create a ComfyUI workflow to finish the following task:

task-instruction

## Analysis

Based on the instruction, analyze the core requirements (e.g. object, pose, style, etc.) and the expected paradigm (e.g., text-to-image, image-to-image, image-to-video, etc.), so that we can retrieve relevant workflows for your reference. You should not consider the quality unless specific requirements (e.g. upscaling, interpolation, refinement, etc.) are mentioned. Note that you do not need to provide the workflow. Make sure your analysis is clear and concise within a single paragraph.


-------------------------------- Program Status --------------------------------
failed to generate workflow: Client.__init__() got an unexpected keyword argument 'proxies'
```

A similar issue here --> https://community.openai.com/t/error-with-openai-1-56-0-client-init-got-an-unexpected-keyword-argument-proxies/1040332

However I am attempting to use local ollama at 10.64.201.1
